### ISSUE TITLE
Why is OP_MODE_SERVER disabled?

### ISSUE THREAD

**Issue by Napsty** [troglobit/omping#3]
In cli.c the server mode is marked as temporarily disabled:

```
		case 'O':
			if (strcmp(optarg, "normal") == 0) {
				instance->op_mode = OMPING_OP_MODE_NORMAL;
			/*
			 * Temporarily disabled
			 *
			} else if (strcmp(optarg, "server") == 0) {
				*op_mode = OMPING_OP_MODE_SERVER;
			*/
			} else if (strcmp(optarg, "client") == 0) {
				instance->op_mode = OMPING_OP_MODE_CLIENT;
			} else {
				warnx("illegal parameter, -O argument -- %s", optarg);
				goto error_usage_exit;
			}
			break;
```

What's the reason for this?

By manually enabling it in the code:

```
		case 'O':
			if (strcmp(optarg, "normal") == 0) {
				instance->op_mode = OMPING_OP_MODE_NORMAL;
			} else if (strcmp(optarg, "server") == 0) {
				instance->op_mode = OMPING_OP_MODE_SERVER;
			} else if (strcmp(optarg, "client") == 0) {
				instance->op_mode = OMPING_OP_MODE_CLIENT;
			} else {
				warnx("illegal parameter, -O argument -- %s", optarg);
				goto error_usage_exit;
			}
			break;
```

This actually seems to work. 
I launched omping on one side (server side) in server mode:

```
# ./omping -p 9999 -O server myip clientip
```

And on the client side in client mode:

```
# ./omping -p 9999 -c 10 -O client myip serverip
```

All worked. Client correctly stopped after 10 counts, server continued to run.

So what's the reason for this being disabled in the code?

And maybe another question: Is this the correct repo to ask this question? I'm kind of confused whether https://github.com/troglobit/omping or https://github.com/jfriesse/omping is the upstream repository for omping.

**Comment by troglobit** [comment]
No clue really why it was disbled. If it works we should enable it :)

When RedHat shut down its hosting repo this tool got lost for a while, so I "adopted" it before @jfriesse pushed his.  I haven't really had time to continue working on it.  Maybe @jfriesse is appy to continue shepherding it?

**Comment by jfriesse** [comment]
@Napsty Reason is described in the issue https://github.com/jfriesse/omping/issues/2 . The issue may look easy to solve, but it needs also some kind of garbage collecting of dead clients (to prevent DOS attack).

Second question is a bit tricky. As you may notice, I'm original author of omping so I would say use my repo :), but @troglobit decided to do the fork (sadly with same name what I find really unfortunate) and release 0.0.5 what was basically just git master. So it may look like a newer version.

@troglobit As you noticed, I'm shepherding omping, but sadly not as much as I would like to (as usually, not enough time and higher priorities like https://github.com/corosync/corosync, https://github.com/corosync/corosync-qdevice, ...). Also I really find unfortunate your choice of using same name. And I'm really talking just about name, forking itself is essence of open source and I really appreciate any fork which makes "dead" project alive, so omping-ng/nomping/yaomping/... would be just fine by me. Anyway, it had happened so I would suggest collaborate to prevent future confusion.

- Are there any patches which you would like to contribute? As I've seen, it's mostly about adding autotools and simplify Makefile. Honestly, I'm not too big fan of autotools as long as they are not really needed. Makefile is different story. The reason why it was written in a way it was written is because of portability - it is basically largest subset of GNU make/OpenBSD make and Solaris make.

- It looks like you've made packages for (at least) Debian. Would you mind to update them if I release 0.0.6 (to make version bigger than 0.0.5) with my repo link as primary source?

**Comment by Napsty** [comment]
Uh oh. I started Minesweeper.

You guys need to decide this on your own, but from an outside perspective I see that both of you say there's not much time to maintain omping. As it is equal in this factor (maintainer time), I suggest to backport relevant changes to the original upstream project from @jfriesse and use Jan's repo as the official omping repository for current and future developments. Maybe you can even share the same authoring permissions on that repo.

Concerning https://github.com/jfriesse/omping/issues/2: Yep, that explanation makes sense. But if I understand correctly, by using different ports (second server instance listening on another port, second client connecting to this port) this could be worked around? 

And to avoid that an unwanted client shoots down the master add an optional auth mechanism (kind of similar to what keepalived is doing)? I'm not a C programmer so it would take me two years to wrap my head around it but maybe you'd already know how to do this?

**Comment by troglobit** [comment]
@jfriesse I think the best course of action is for me to archive this project.

I only adopted it here on GitHub because: a) it seemed abandoned at the time, fedorahosted.org was being retired, and b) I needed something for testing and had to cross-compile to different archs.   It was not a fork as such, more of a continuation.

I think it's very unlikely I'll ever get time to sit down and do something useful (rename it, develop it further), maybe one day I can find some time to port useful patches to your repo.
